param(
    [string]$StatusPath = "docs/backlog/story-status.json",
    [string]$OutputPath = "PROJECT_STATUS.md",
    [int]$LatestCount = 5
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$statusFile = Join-Path $repoRoot $StatusPath
$outputFile = Join-Path $repoRoot $OutputPath
$backlogRoot = Join-Path $repoRoot "docs/backlog"

if (-not (Test-Path $statusFile)) {
    throw "Status file '$StatusPath' was not found."
}

$storyStatus = Get-Content $statusFile -Raw | ConvertFrom-Json
$backlogFiles = Get-ChildItem -Path $backlogRoot -Filter "EPIC-*.md" | Sort-Object Name

$stories = foreach ($file in $backlogFiles) {
    $epicName = $null

    foreach ($line in Get-Content $file.FullName) {
        if (-not $epicName -and $line -match "^#\s+(Epic\s+\d+:\s+.+)$") {
            $epicName = $Matches[1]
            continue
        }

        if ($line -match "^#{2,3}\s+(SC-[A-Z]+-\d{2,3})(?:\s+-\s+|\s+)(.+)$") {
            [pscustomobject]@{
                Id = $Matches[1]
                Title = $Matches[2].Trim()
                Epic = $epicName
            }
        }
    }
}

$storyLookup = @{}
foreach ($story in $stories) {
    $storyLookup[$story.Id] = $story
}

$completedLookup = @{}
foreach ($entry in $storyStatus.completedStories) {
    $completedLookup[$entry.id] = $entry
}

$noteLookup = @{}
foreach ($note in $storyStatus.notes) {
    $noteLookup[$note.id] = $note.note
}

$storyRows = foreach ($story in $stories) {
    $completion = $completedLookup[$story.Id]
    [pscustomobject]@{
        Id = $story.Id
        Title = $story.Title
        Epic = $story.Epic
        IsCompleted = $null -ne $completion
        CompletedOn = if ($completion) { [string]$completion.completedOn } else { $null }
        Commit = if ($completion) { [string]$completion.commit } else { $null }
    }
}

$totalStories = $storyRows.Count
$completedStories = @($storyRows | Where-Object IsCompleted)
$completedCount = $completedStories.Count
$remainingCount = $totalStories - $completedCount
$percentComplete = if ($totalStories -eq 0) { 0 } else { [math]::Round(($completedCount / $totalStories) * 100, 1) }

$epicSummary = foreach ($epicGroup in ($storyRows | Group-Object Epic | Sort-Object Name)) {
    $epicCompleted = @($epicGroup.Group | Where-Object IsCompleted).Count
    $epicTotal = $epicGroup.Count
    [pscustomobject]@{
        Epic = $epicGroup.Name
        Completed = $epicCompleted
        Total = $epicTotal
        Percent = if ($epicTotal -eq 0) { 0 } else { [math]::Round(($epicCompleted / $epicTotal) * 100, 1) }
    }
}

$latestStories = foreach ($entry in $storyStatus.completedStories | Select-Object -First $LatestCount) {
    $story = $storyLookup[$entry.id]
    if ($null -eq $story) {
        continue
    }

    [pscustomobject]@{
        Id = $story.Id
        Title = $story.Title
        Epic = $story.Epic
        CompletedOn = [string]$entry.completedOn
        Commit = [string]$entry.commit
    }
}

$pendingStories = @(
    $storyRows |
        Where-Object { -not $_.IsCompleted } |
        Select-Object -First 10
)

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# Shrimp Cam Project Status")
$lines.Add("")
$lines.Add("> Auto-generated by `scripts/update-project-status.ps1`. Do not edit manually.")
$lines.Add("")
$lines.Add("## Overview")
$lines.Add("")
$lines.Add("| Metric | Value |")
$lines.Add("| --- | --- |")
$lines.Add("| Last refreshed | $(Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz") |")
$lines.Add("| Total stories | $totalStories |")
$lines.Add("| Accepted stories | $completedCount |")
$lines.Add("| Remaining stories | $remainingCount |")
$lines.Add("| Overall completion | $percentComplete% |")
$lines.Add("")
$lines.Add("## Epic Progress")
$lines.Add("")
$lines.Add("| Epic | Accepted | Total | Complete |")
$lines.Add("| --- | --- | --- | --- |")

foreach ($epic in $epicSummary) {
    $lines.Add("| $($epic.Epic) | $($epic.Completed) | $($epic.Total) | $($epic.Percent)% |")
}

$lines.Add("")
$lines.Add("## Latest Completed Stories")
$lines.Add("")
$lines.Add("| Story | Title | Epic | Completed On | Commit |")
$lines.Add("| --- | --- | --- | --- | --- |")

foreach ($story in $latestStories) {
    $lines.Add("| $($story.Id) | $($story.Title) | $($story.Epic) | $($story.CompletedOn) | $($story.Commit) |")
}

$lines.Add("")
$lines.Add("## Next Unaccepted Stories")
$lines.Add("")
$lines.Add("| Story | Title | Epic |")
$lines.Add("| --- | --- | --- |")

foreach ($story in $pendingStories) {
    $lines.Add("| $($story.Id) | $($story.Title) | $($story.Epic) |")
}

if ($storyStatus.notes.Count -gt 0) {
    $lines.Add("")
    $lines.Add("## Notes")
    $lines.Add("")

    foreach ($storyId in $noteLookup.Keys | Sort-Object) {
        if ($storyLookup.ContainsKey($storyId)) {
            $lines.Add(("- {0}: {1}" -f $storyId, $noteLookup[$storyId]))
        }
        else {
            $lines.Add(("- {0}: {1}" -f $storyId, $noteLookup[$storyId]))
        }
    }
}

Set-Content -Path $outputFile -Value $lines -Encoding utf8
